# Generated by Django 2.1.2 on 2018-12-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railwayapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Train',
            },
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
    ]
